parameters:
#    hezten_message.example.class: Hezten\MessageBundle\Example

services:
#    hezten_message.example:
#        class: %hezten_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
